services:
  api:
    image: tracker-api:latest
    shm_size: 1g
    restart: always
    environment:
      DATABASE_HOST: 172.17.0.1
      RPC_HOST: 172.17.0.1
    ports:
      - "3003:3003"
  flur:
    image: flur:latest
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: https://api.btccat.org
      NEXT_IN_API_URL: http://172.17.0.1:3003
      PORT: 3005
    entrypoint: []
    command: "yarn start"
    ports:
      - "3005:3005"
    logging:
      driver: "json-file"
      options:
        labels: "env,filebeat,name"
        max-size: "1g"
        max-file: "3"